version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
before_build:
- ps: dotnet restore
build:
  project: S22.Mail.sln
  publish_nuget: true
  verbosity: minimal
on_success:
- ps: dotnet pack .\S22.Mail.sln --no-build -c Release